---
name: Perl-Critic
version: 0.13
author:
  - Jeffrey Thalhammer <thaljef@cpan.org>
abstract: Critique Perl source for style and standards
license: perl
requires:
  Config::Tiny: 2
  File::Spec: 0
  IO::String: 0
  List::MoreUtils: 0
  List::Util: 0
  PPI: 1.103
  Pod::PlainText: 0
  Pod::Usage: 0
  String::Format: 1.13
recommends:
  Perl::Tidy: 0
build_requires:
  Test::More: 0
provides:
  Perl::Critic:
    file: lib/Perl/Critic.pm
    version: 0.13
  Perl::Critic::Config:
    file: lib/Perl/Critic/Config.pm
    version: 0.13
  Perl::Critic::Policy:
    file: lib/Perl/Critic/Policy.pm
    version: 0.13
  Perl::Critic::Policy::BuiltinFunctions::ProhibitLvalueSubstr:
    file: lib/Perl/Critic/Policy/BuiltinFunctions/ProhibitLvalueSubstr.pm
    version: 0.13
  Perl::Critic::Policy::BuiltinFunctions::ProhibitSleepViaSelect:
    file: lib/Perl/Critic/Policy/BuiltinFunctions/ProhibitSleepViaSelect.pm
    version: 0.13
  Perl::Critic::Policy::BuiltinFunctions::ProhibitStringyEval:
    file: lib/Perl/Critic/Policy/BuiltinFunctions/ProhibitStringyEval.pm
    version: 0.13
  Perl::Critic::Policy::BuiltinFunctions::RequireBlockGrep:
    file: lib/Perl/Critic/Policy/BuiltinFunctions/RequireBlockGrep.pm
    version: 0.13
  Perl::Critic::Policy::BuiltinFunctions::RequireBlockMap:
    file: lib/Perl/Critic/Policy/BuiltinFunctions/RequireBlockMap.pm
    version: 0.13
  Perl::Critic::Policy::BuiltinFunctions::RequireGlobFunction:
    file: lib/Perl/Critic/Policy/BuiltinFunctions/RequireGlobFunction.pm
    version: 0.13
  Perl::Critic::Policy::ClassHierarchies::ProhibitOneArgBless:
    file: lib/Perl/Critic/Policy/ClassHierarchies/ProhibitOneArgBless.pm
    version: 0.13
  Perl::Critic::Policy::CodeLayout::ProhibitHardTabs:
    file: lib/Perl/Critic/Policy/CodeLayout/ProhibitHardTabs.pm
    version: 0.13
  Perl::Critic::Policy::CodeLayout::ProhibitParensWithBuiltins:
    file: lib/Perl/Critic/Policy/CodeLayout/ProhibitParensWithBuiltins.pm
    version: 0.13
  Perl::Critic::Policy::CodeLayout::ProhibitQuotedWordLists:
    file: lib/Perl/Critic/Policy/CodeLayout/ProhibitQuotedWordLists.pm
    version: 0.13
  Perl::Critic::Policy::CodeLayout::RequireTidyCode:
    file: lib/Perl/Critic/Policy/CodeLayout/RequireTidyCode.pm
    version: 0.13
  Perl::Critic::Policy::CodeLayout::RequireTrailingCommas:
    file: lib/Perl/Critic/Policy/CodeLayout/RequireTrailingCommas.pm
    version: 0.13
  Perl::Critic::Policy::ControlStructures::ProhibitCStyleForLoops:
    file: lib/Perl/Critic/Policy/ControlStructures/ProhibitCStyleForLoops.pm
    version: 0.13
  Perl::Critic::Policy::ControlStructures::ProhibitCascadingIfElse:
    file: lib/Perl/Critic/Policy/ControlStructures/ProhibitCascadingIfElse.pm
    version: 0.13
  Perl::Critic::Policy::ControlStructures::ProhibitPostfixControls:
    file: lib/Perl/Critic/Policy/ControlStructures/ProhibitPostfixControls.pm
    version: 0.13
  Perl::Critic::Policy::ControlStructures::ProhibitUnlessBlocks:
    file: lib/Perl/Critic/Policy/ControlStructures/ProhibitUnlessBlocks.pm
    version: 0.13
  Perl::Critic::Policy::ControlStructures::ProhibitUntilBlocks:
    file: lib/Perl/Critic/Policy/ControlStructures/ProhibitUntilBlocks.pm
    version: 0.13
  Perl::Critic::Policy::InputOutput::ProhibitBacktickOperators:
    file: lib/Perl/Critic/Policy/InputOutput/ProhibitBacktickOperators.pm
    version: 0.13
  Perl::Critic::Policy::InputOutput::ProhibitBarewordFileHandles:
    file: lib/Perl/Critic/Policy/InputOutput/ProhibitBarewordFileHandles.pm
    version: 0.13
  Perl::Critic::Policy::InputOutput::ProhibitOneArgSelect:
    file: lib/Perl/Critic/Policy/InputOutput/ProhibitOneArgSelect.pm
    version: 0.13
  Perl::Critic::Policy::InputOutput::ProhibitTwoArgOpen:
    file: lib/Perl/Critic/Policy/InputOutput/ProhibitTwoArgOpen.pm
    version: 0.13
  Perl::Critic::Policy::Miscellanea::RequireRcsKeywords:
    file: lib/Perl/Critic/Policy/Miscellanea/RequireRcsKeywords.pm
    version: 0.13
  Perl::Critic::Policy::Modules::ProhibitMultiplePackages:
    file: lib/Perl/Critic/Policy/Modules/ProhibitMultiplePackages.pm
    version: 0.13
  Perl::Critic::Policy::Modules::ProhibitSpecificModules:
    file: lib/Perl/Critic/Policy/Modules/ProhibitSpecificModules.pm
    version: 0.13
  Perl::Critic::Policy::Modules::RequireBarewordIncludes:
    file: lib/Perl/Critic/Policy/Modules/RequireBarewordIncludes.pm
    version: 0.13
  Perl::Critic::Policy::Modules::RequireEndWithOne:
    file: lib/Perl/Critic/Policy/Modules/RequireEndWithOne.pm
    version: 0.13
  Perl::Critic::Policy::Modules::RequireExplicitPackage:
    file: lib/Perl/Critic/Policy/Modules/RequireExplicitPackage.pm
    version: 0.13
  Perl::Critic::Policy::Modules::RequireVersionVar:
    file: lib/Perl/Critic/Policy/Modules/RequireVersionVar.pm
    version: 0.13
  Perl::Critic::Policy::NamingConventions::ProhibitMixedCaseSubs:
    file: lib/Perl/Critic/Policy/NamingConventions/ProhibitMixedCaseSubs.pm
    version: 0.13
  Perl::Critic::Policy::NamingConventions::ProhibitMixedCaseVars:
    file: lib/Perl/Critic/Policy/NamingConventions/ProhibitMixedCaseVars.pm
    version: 0.13
  Perl::Critic::Policy::RegularExpressions::RequireExtendedFormatting:
    file: lib/Perl/Critic/Policy/RegularExpressions/RequireExtendedFormatting.pm
    version: 0.13
  Perl::Critic::Policy::RegularExpressions::RequireLineBoundaryMatching:
    file: lib/Perl/Critic/Policy/RegularExpressions/RequireLineBoundaryMatching.pm
    version: 0.13
  Perl::Critic::Policy::Subroutines::ProhibitBuiltinHomonyms:
    file: lib/Perl/Critic/Policy/Subroutines/ProhibitBuiltinHomonyms.pm
    version: 0.13
  Perl::Critic::Policy::Subroutines::ProhibitExplicitReturnUndef:
    file: lib/Perl/Critic/Policy/Subroutines/ProhibitExplicitReturnUndef.pm
    version: 0.13
  Perl::Critic::Policy::Subroutines::ProhibitSubroutinePrototypes:
    file: lib/Perl/Critic/Policy/Subroutines/ProhibitSubroutinePrototypes.pm
    version: 0.13
  Perl::Critic::Policy::Subroutines::RequireFinalReturn:
    file: lib/Perl/Critic/Policy/Subroutines/RequireFinalReturn.pm
    version: 0.13
  Perl::Critic::Policy::TestingAndDebugging::RequirePackageStricture:
    file: lib/Perl/Critic/Policy/TestingAndDebugging/RequirePackageStricture.pm
    version: 0.13
  Perl::Critic::Policy::TestingAndDebugging::RequirePackageWarnings:
    file: lib/Perl/Critic/Policy/TestingAndDebugging/RequirePackageWarnings.pm
    version: 0.13
  Perl::Critic::Policy::ValuesAndExpressions::ProhibitConstantPragma:
    file: lib/Perl/Critic/Policy/ValuesAndExpressions/ProhibitConstantPragma.pm
    version: 0.13
  Perl::Critic::Policy::ValuesAndExpressions::ProhibitEmptyQuotes:
    file: lib/Perl/Critic/Policy/ValuesAndExpressions/ProhibitEmptyQuotes.pm
    version: 0.13
  Perl::Critic::Policy::ValuesAndExpressions::ProhibitInterpolationOfLiterals:
    file: lib/Perl/Critic/Policy/ValuesAndExpressions/ProhibitInterpolationOfLiterals.pm
    version: 0.13
  Perl::Critic::Policy::ValuesAndExpressions::ProhibitLeadingZeros:
    file: lib/Perl/Critic/Policy/ValuesAndExpressions/ProhibitLeadingZeros.pm
    version: 0.13
  Perl::Critic::Policy::ValuesAndExpressions::ProhibitNoisyQuotes:
    file: lib/Perl/Critic/Policy/ValuesAndExpressions/ProhibitNoisyQuotes.pm
    version: 0.13
  Perl::Critic::Policy::ValuesAndExpressions::RequireInterpolationOfMetachars:
    file: lib/Perl/Critic/Policy/ValuesAndExpressions/RequireInterpolationOfMetachars.pm
    version: 0.13
  Perl::Critic::Policy::ValuesAndExpressions::RequireNumberSeparators:
    file: lib/Perl/Critic/Policy/ValuesAndExpressions/RequireNumberSeparators.pm
    version: 0.13
  Perl::Critic::Policy::ValuesAndExpressions::RequireQuotedHeredocTerminator:
    file: lib/Perl/Critic/Policy/ValuesAndExpressions/RequireQuotedHeredocTerminator.pm
    version: 0.13
  Perl::Critic::Policy::ValuesAndExpressions::RequireUpperCaseHeredocTerminator:
    file: lib/Perl/Critic/Policy/ValuesAndExpressions/RequireUpperCaseHeredocTerminator.pm
    version: 0.13
  Perl::Critic::Policy::Variables::ProhibitLocalVars:
    file: lib/Perl/Critic/Policy/Variables/ProhibitLocalVars.pm
    version: 0.13
  Perl::Critic::Policy::Variables::ProhibitPackageVars:
    file: lib/Perl/Critic/Policy/Variables/ProhibitPackageVars.pm
    version: 0.13
  Perl::Critic::Policy::Variables::ProhibitPunctuationVars:
    file: lib/Perl/Critic/Policy/Variables/ProhibitPunctuationVars.pm
    version: 0.13
  Perl::Critic::Utils:
    file: lib/Perl/Critic/Utils.pm
    version: 0.13
  Perl::Critic::Violation:
    file: lib/Perl/Critic/Violation.pm
    version: 0.13
generated_by: Module::Build version 0.2611
